export const APP_LOGIN_START = "APP_LOGIN_START";
export const APP_LOGIN = "APP_LOGIN";
export const APP_LOGIN_FAIL = "APP_LOGIN_FAIL";
export const APP_LOGOUT = "APP_LOGOUT";

export const APP_MOCKCATEGORY_START = "APP_MOCKCATEGORY_START";
export const APP_MOCKCATEGORY = "APP_MOCKCATEGORY";
export const APP_MOCKCATEGORY_FAIL = "APP_MOCKCATEGORY_FAIL";

export const APP_MOCKTEST_START = "APP_MOCK_START";
export const APP_MOCKTEST = "APP_MOCKTEST";
export const APP_MOCKTEST_FAIL = "APP_MOCKTEST_FAIL";

